//-----
// Sfx packet definition file.
// Only editable by someone.
//-----

//-----
//# PACKET: Birds
// Last Edited: 11/18/97 - 11:10:51.
// File Format: 1.0.
//-----
#define SFX_BIRDS         		 0
//# NAME: Birds
//# PRIORITY: 200
//# TYPE: 6
//# FLAGS: 2
//# SNDS: 17
//#-----
//#     SAMPLE: 98447_505301-lq
//#     FREQ: 44100
//#     FREQDEV: 500
//#     VOLUME: 70
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 238056_4183089-lq
//#     FREQ: 44100
//#     FREQDEV: 99
//#     VOLUME: 0
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 259548_2316086-lq
//#     FREQ: 44100
//#     FREQDEV: 50
//#     VOLUME: 70
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 259548_2316086-lq
//#     FREQ: 44100
//#     FREQDEV: 6666
//#     VOLUME: 0
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 424141_7707368-lq
//#     FREQ: 44100
//#     FREQDEV: 50
//#     VOLUME: 80
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 238056_4183089-lq
//#     FREQ: 22000
//#     FREQDEV: 50
//#     VOLUME: 80
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 424141_7707368-lq
//#     FREQ: 44100
//#     FREQDEV: 0
//#     VOLUME: 80
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 424141_7707368-lq
//#     FREQ: 44100
//#     FREQDEV: 50
//#     VOLUME: 70
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 424141_7707368-lq
//#     FREQ: 44100
//#     FREQDEV: 70
//#     VOLUME: 70
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 98447_505301-lq
//#     FREQ: 44100
//#     FREQDEV: 0
//#     VOLUME: 80
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 238056_4183089-lq
//#     FREQ: 44100
//#     FREQDEV: 0
//#     VOLUME: 70
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 238056_4183089-lq
//#     FREQ: 44100
//#     FREQDEV: 7777
//#     VOLUME: 0
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 238056_4183089-lq
//#     FREQ: 44100
//#     FREQDEV: 66
//#     VOLUME: 0
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 238056_4183089-lq
//#     FREQ: 44100
//#     FREQDEV: 55
//#     VOLUME: 0
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 259548_2316086-lq
//#     FREQ: 16050
//#     FREQDEV: 1200
//#     VOLUME: 0
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 98447_505301-lq
//#     FREQ: 44100
//#     FREQDEV: 10
//#     VOLUME: 0
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0
//#-----
//#     SAMPLE: 98447_505301-lq
//#     FREQ: 44100
//#     FREQDEV: 1000
//#     VOLUME: 0
//#     LOOP: 0
//#     ATTACK: 0
//#     RELEASE: 0

